### ISSUE TITLE
PR1 to procedures only happening in first PR1

### ISSUE THREAD

**Issue by camila8** [microsoft/FHIR-Converter#159]
PR1 to Procedure is only happening for the first PR1. The converter should loop through all the PR1s a message has and convert each one into a procedure resource in the bundle.

**Comment by ranvijaykumar** [comment]
Thanks for reporting. We will look into it.

**Comment by ACMoretxj** [comment]
It will be fixed in the following pull-request, thanks for your feedback :)

**Comment by ACMoretxj** [comment]
This pull request #160 is meant to solve this issue, please validate your case after this PR is merged.

**Comment by ACMoretxj** [comment]
We have the latest release [V3.2](https://github.com/microsoft/FHIR-Converter/releases/tag/v3.2), in which this issue has been solved.

**Comment by camila8** [comment]
Still get an error once I pulled the new release:
[cid:image001.png@01D6EA51.99A1B2D0]

Camila Altman, MS
(she/her/hers)
Research and Development Solutions Architect
Information Services
Northwestern Memorial Healthcare
312.695.4321 office
cbenaim@nm.org<http://www.nm.org/>

[NM-Logo-stacked-2090.png]

**Comment by camila8** [comment]
Our engine(the FHIR-Converter project) and the VS Code extension are not the same project and will not be released simultaneously.
The engine has been updated and you can use it in command line, while the extension still need a set of tests and will be updated later on. I'll let you know when the VS Code extension ready.

Thanks,
Ferris

From: Altman, Camila <cbenaim@nm.org>
Sent: Thursday, January 14, 2021 10:45 PM
To: microsoft/FHIR-Converter <reply@reply.github.com>
Cc: Ferris Tien <Ferris.Tian@microsoft.com>
Subject: [EXTERNAL] RE: [microsoft/FHIR-Converter] PR1 to procedures only happening in first PR1 (#159)

Still get an error once I pulled the new release:
[cid:image001.png@01D6EB2A.6BA24A00]

Camila Altman, MS
(she/her/hers)
Research and Development Solutions Architect
Information Services
Northwestern Memorial Healthcare
312.695.4321 office
cbenaim@nm.org<https://nam06.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.nm.org%2F&data=04%7C01%7CFerris.Tian%40microsoft.com%7C2ffff1c0fac04a8f656708d8b89b09a2%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637462323328453561%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=DoPUFkqPrAa7eLQwqL%2B%2Bzh5tbEWd0tnNKyoRRq0rQfs%3D&reserved=0>

[NM-Logo-stacked-2090.png]

**Comment by ACMoretxj** [comment]
Our engine(the FHIR-Converter project) and the VS Code extension are not the same project and will not be released simultaneously.
The engine has been updated and you can use it in command line, while the extension still need a set of tests and will be updated later on. I’ll let you know when the VS Code extension ready.
